# Generated by Django 4.2.21 on 2025-05-23 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('priority', models.CharField(choices=[('high', 'Высокий'), ('medium', 'Средний'), ('low', 'Низкий')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Ожидает выполнения'), ('in_progress', 'В процессе'), ('completed', 'Выполнена')], max_length=20)),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
    ]
